
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int L_BRK = 15;
  public static final int FUNCTION = 5;
  public static final int CONST = 2;
  public static final int EQUALS = 21;
  public static final int STRCONST = 35;
  public static final int REL = 30;
  public static final int R_BOX = 14;
  public static final int R_PAR = 12;
  public static final int ARRAY = 4;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int TYPE = 32;
  public static final int INTCONST = 33;
  public static final int OR = 28;
  public static final int R_BRK = 16;
  public static final int COMMA = 17;
  public static final int DIV = 25;
  public static final int EOL = 18;
  public static final int MAIN = 7;
  public static final int IF = 10;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int ADD = 22;
  public static final int MOD = 26;
  public static final int IDENT = 31;
  public static final int READ = 19;
  public static final int WHILE = 9;
  public static final int BOOLCONST = 34;
  public static final int L_BOX = 13;
  public static final int L_PAR = 11;
  public static final int SUB = 23;
  public static final int VAR = 3;
  public static final int PROCEDURE = 6;
  public static final int PRINT = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONST",
  "VAR",
  "ARRAY",
  "FUNCTION",
  "PROCEDURE",
  "MAIN",
  "RETURN",
  "WHILE",
  "IF",
  "L_PAR",
  "R_PAR",
  "L_BOX",
  "R_BOX",
  "L_BRK",
  "R_BRK",
  "COMMA",
  "EOL",
  "READ",
  "PRINT",
  "EQUALS",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "MOD",
  "AND",
  "OR",
  "NOT",
  "REL",
  "IDENT",
  "TYPE",
  "INTCONST",
  "BOOLCONST",
  "STRCONST"
  };
}

